= 法律职业伦理
:icons: font
:sectnums:
:toc: left

== 总论

法律职业人员:: 具有共同的政治素养、业务能力职业伦理和从业资格要求，专门从事立法、执法、司法、法律服务和法律教育研究工作的职业群体。

法律职业精神:: 法律职业群体长期的专业服务实践中逐渐形成的价值理念、行为方式、职业操守、精神风貌、制度规范以及相关物质表现的总称，是法律职业群体共同具备的人文素养和专业水平的集中反映。

法律职业伦理:: 针对法律职业人员的一种特殊的职业规范，具体来说是指法官、检察官、律师及公证员等法律职业人员在其职务活动中所应遵循的行为规范的总和。

担任**法官、检察官、律师、公证员、法律顾问、仲裁员（法律类）及政府部门中从事行政处罚决定审核、行政复议、行政裁决的人员**，应当取得国家统一法律职业资格。

.法律职业人员分类
. 应用类，律师、法官、检察官、立法人员、仲裁员、公证员
. 学术类，主要指法律教师和法律研究人员
. 法律辅助技术类，主要职责是辅助律师、法官和检察官

法律职业可归纳为具有共同的政治素养、专业能力、职业伦理和从业资格要求，专门从事立法、执法、司法、法律服务和法律教育研究等工作的职业。

.法律职业的特征
. 有专业技术理性（从知识和专业角度，要要经过科班学习和持续学习）
. 有自主性、自治性（有共同思维、技术理性、共同理念、共同渊源。自治性意味着不接受纵向命令，这是司法独立的源头）
. 有专业门槛（专业槽）
. 有专业伦理（公共性）：专业人士不只追求他们自已的利益和成功，他们要有为公众服务的精神

.天职观念及其作用
. 制约专业人士将私利凌驾于公共利益之上的倾向
. 为重建律师和客户的关系打开一扇门
. 帮助律师以正确的态度看待律师的财富和工作问题
. 能够扩展律师的道德视野


.职业精神的功能
. 精神引领
. 理念导向
. 行为约束
. 行为评价
. 形象塑造

.伦理和道德
* 伦理侧重于反映人伦关系以及维持人伦关系所必须遵循的规则，是自律与他律的有机统一
* 道德侧重于反映道德活动或道德活动主体自身行为的应当，强调自律


.人民政权的法律职业伦理
* 根据地以来的政法性伦理传统：忠于党，忠于人民，忠于法律
* 新时代的社会主义法治伦理
** 忠诚：忠于党、忠于国家、忠于人民、忠于法律
** 为民：司法为民，努力让人民群众在每一个司法案件中感受到公平正义

== 法官职业伦理

伦理角度，要成为一名法官，核心要素是：“外化于形的职业操守”“内化于心的道德准则”。

法官职业伦理:: 法官在从事业内行为和业外活动中应遵循的行为规范和道德准则的总和。

.法官职业伦理的特征
. 主体是法官
. 客体是法官的行为（包括业外活动）
. 法律与道德双重性
. 他律性

[quote,2019年《中华人民共和国法官法》第2条]
____
法官是依法行使国家审判权的审判人员，包括最高人民法院、地方各级人民法院和军事法院等专门人民法院的院长、副院长、审判委员会委员、庭长、副庭长和审判员。
____

[quote,2010年最高人民法院重新印发的《中华人民共和国法官职业道德基本准则》第27条]
____
人民陪审员依法履行审判职责期间，应当遵守本准则。人民法院其他工作人员参照执行本准则。
____

这里的“人民法院其他工作人员”根据分工的不同，有书记员、执行员、司法警察、行政后勤人员等。由《准则》可知，法官的职业道德准则对《法官法》中定义的法官之外的其他法官队伍中的工作人员也具备约束力。

=== 法官执业中的行为准则规范

=== 忠诚司法事业

. 牢固树立社会主义法治理念，忠于党、忠于国家、忠于人民、忠于法律
. 坚持和维护中国特色社会主义司法制度，认真贯彻落实依法治国基本方略，自觉维护法律的权威和尊严
. 热爱司法事业，珍惜法官荣誉，坚持职业操守，恪守法官良知，以维护社会公平正义为已任
. 维护国家利益，遵守政治纪律，保守国家秘密和审判工作秘密，不从事或参与有损国家利益和司法权威的活动，不发表有损国家利益和司法权威的言论

=== 保证司法公正
. 维护审判独立
.. 外部独立
.. 体系内独立
.. 思想独立
. 以事实为依据，以法律为准绳
. 坚持程序公正
. 提高司法效率
.. 树立效率意识
.. 严守时限规定
... 开庭时间不随意更改
... 不迟到早退缺席
. 公开审判
. 遵守回避
.. 角色伦理：一个人不能成为自已事务的法官
.. 避免利益冲突

.审判人员公务回避的情形
. 是本案当事人或者与当事人有近亲属关系
. 本人或者其近亲属与本案有利害关系的
. 担任过本案的证人、翻译人员、鉴定人、勘验人、诉讼代理人、辩护人
. 与本案的诉讼代理人、辩护人有夫妻、父母、子女或者兄弟姐妹关系
. 与本案当事人之间存在其他利害关系，可能影响案件公正审理

.职务回避
* 任职回避：《法官法》规定任职回避包括“法官之间有夫妻关系、直系血亲关系、三代以内旁系血亲以及近姻亲关系的，不得同时担任下列职务：第一，同一人民法院的院长、副院长、审判委员会委员、庭长、副庭长；第二，同一人民法院的院长、副院长和审判员、助理审判员；第三，同一审判庭的庭长、副庭长、审判员、助理审判员；第四，上下相邻两级人民法院的院长、副院长。”
* 离职回避：法官的离职回避包括，“法官从人民法院离任后二年内，不得以律师身份担任诉讼代理人或者辩护人。法官从人民法院离任后，不得担任原任职法院办理案件的诉讼代理人或者辩护人。法官的配偶、子女不得担任该法官所任职法院办理案件的诉讼代理人或者辩护人。”

=== 确保司法廉洁

.司法廉洁丧失的原因
. 时代原因
. 内部私欲膨胀
. 外部利益、情色诱惑和各种拉拢、围猎

.防范丧失司法廉洁
. 对司法心存敬畏（不敢）
. 加强司法廉政制度建设（不能）
. 加强中国传统文化学习，践行忠诚、公正、为民伦理（不想）

=== 坚持司法为民

《法官行为规范》要求法官一心为民，落实司法为民的各项规定和要求，做到听民声、察民情、知民意，坚持能动司法，树立服务意识，做好诉讼指导、风险提示、法律释明等便民服务，避免“冷硬横推”等不良作风。

《准则》第19条明确规定，法官要牢固树立以人为本、司法为民的理念，强化群众观念，重视群众诉求，关注群众感受，自觉维护人民群众的合法权益。

=== 维护司法形象

. 严守司法礼仪
. 培养健康情趣

== 检察官职业伦理

概念、特点、作用，不再赘述。

[quote,中华人民共和国检察官职业道德基本准则（2016年11月4日最高人民检察院第十二届检察委员会第五十七次会议通过）]
____
第一条：坚持**忠诚**footnote:[ 忠于党、忠于国家，忠于人民，忠于宪法和法律，忠于检察事业。]品格，永葆政治本色。

第二条：坚持**为民**宗旨，保障人民权益。

第三条：坚持**担当**footnote:[敢于监督，善于监督，勇于承担责任。]精神，强化法律监督。

第四条：坚持**公正**footnote:[独立、**回避**、重视证据、遵守程序。]理念，维护法制统一。

第五条：坚持**廉洁**操守，自觉接受监督。
____

=== 回避

==== 公务回避

[quote,《最高人民法院关于审判人员在诉讼活动中执行回避制度若干问题的规定》第1条]
____

第一，审判人员是本案当事人或者与当事人有近亲属关系的；第二，本人或者其近亲属与本案有利害关系的；第三，担任过本案的证人、翻译人员、鉴定人、勘验人、诉讼代理人、辩护人的；第四，与本案的诉讼代理人、辩护人有夫妻、父母、子女或者兄弟姐妹关系的；第五，与本案当事人之间存在其他利害关系，可能影响案件公正审理的。
____

==== 任职回避

[quote,《检察官法》第24条]
____
检察官footnote:[指各级人民检察院检察官、书记员、司法行政人员和司法警察。]之间有夫妻关系、直系血亲关系、三代以内旁系血亲以及近姻亲关系的，不得同时担任下列职务：

（一）同一人民检察院的检察长、副检察长、检察委员会委员；

（二）同一人民检察院的检察长、副检察长和检察员；

（三）同一业务部门的检察员；

（四）上下相邻两级人民检察院的检察长、副检察长。
____

[quote,《检察官法》第25条]
____
检察官的配偶、父母、子女有下列情形之一的，检察官应当实行任职回避：

（一）担任该检察官所任职人民检察院辖区内律师事务所的合伙人或者设立人的；

（二）在该检察官所任职人民检察院辖区内以律师身份担任诉讼代理人、辩护人，或者为诉讼案件当事人提供其他有偿法律服务的。
____

== 律师职业伦理

. 坚定信念：坚持党的领导
. 执业为民
. 维护法治
. 追求正义
. 勤勉敬业

