= 国际私法
:icons: font
:sectnums:
:toc: left


== 基本原则

. 国家主权原则
. 平等互利原则
.. 国家间
.. 当事人间
.. 民商事判决域外承认执行中的司法礼让
. 有约必守原则
.. 国家间
.. 当事人间
.. 限制
... 合法的条约或合同
... 情势变更
. 保护弱者原则：在制定、运用、实施和解释国际私法时，应侧重于保护在国际民商事关系中处于弱势一方当事人的合法权益

== 学说史

.国际私法从萌芽到诞生
. 萌芽：万民法
. 西罗马帝国灭亡后400年：种族法时代（属人法时代）
. 9世纪查理曼帝国瓦解和封建制度形成：属地法时代
. 13世纪——18世纪：学说法时期
. 13世纪意大利北部——16世纪传入法国——后来发展于荷兰：法则区别说（theory of statutes）——标志着国际私法理论诞生

=== 法则区别说

==== 意大利

后期注释法学派的集大成者巴托鲁斯（Bartolus）指出了法律冲突的两个基本问题——法律的域内效力与域外效力，提出了解决各城邦之间法律冲突的**法则区别说**（法则两分说），这标志着国际私法的诞生。

.法则的分类
* 人法（statuta personalia）
** 有关人与人之间关系的法则
** 适用于
*** 管辖范围内的人民
*** 身在外国的该城邦属民
** 内容“令人厌恶”，则不具有域外效力，不能被内国所适用：公共秩序保留的雏形
* 物法（statuta realia）
** 有关物的法律关系的法则
** 用于制定者管辖范围之内的物
* 混合法则（statuta mixta）
** 与契约的方式和契约的直接的自然的效果有关

==== 法国

杜摩兰（Dumoulin）——新兴资产阶级——**意思自治**（autonomy of will）。明确提出夫妻财产关系应作为合同问题而非财产问题处理，同时应按照当事人默示的意思适用其最初婚后住所地的习惯法。影响很深远。

达让特莱——封建主阶级——法则三分说——**属地主义**。和杜摩兰观点相反，他反对法律的统一化。法则三分说”在重申人法和物法之区别的同时，提出同时涉及到人和物的法则应单独另成一类，即“混合法则”，即同一法则兼及人和物两个方面，不具有域外效力。提出存疑时视为物法。压缩了域外效力，体现**属地主义**。被荷兰学者继承并向英美传播。

==== 荷兰

以胡伯为代表。继承自达让特莱的属地主义，提出**礼让说**（doctrine of comity）。强调主权原则，强调法的属地性，即只在制定它们的主权者域内有效，适用外国法不是基于它本身有什么域外效力， 而是内国出于“礼让”的考虑。

=== 近代国际私法

==== 德国的法律关系本座说

* 萨维尼
* 相互交往的国家的国际法律共同体
* 国际民商事关系依其本身性质确定**本座**footnote:[任何法律关系都只能和某一特定地区保有最本质的联系。这个特定的地域就是该法律关系的本座（Seat）。]所在地法律


==== 意大利的本国法学说

* 孟西尼
* 国籍是法律选择的最重要的基础

.原则
* 国籍原则：人无论走到哪里都应服从其本国法律的支配，在审理涉外民事案件时，尽可能地适用当事人的本国法
* 意思自治原则：重人的自由，有关债权的法律关系，应适用当事人选择的法律
* 公共秩序原则：旨在维护公共秩序的法律应适用于该国领域内的一切人，不管他是本国人还是外国人

==== 英美学派

* （美）斯托雷的属地法说
** 主权原则：国内法的适用
** 平等原则：域外无效
** 域外效力取决于另一国家的同意（自主决定而非国际习惯法义务）
* （英）戴赛的既得权说（doctrine of vested rights）
** 法官的任务是执行内国法律
** 外国法律在内国不具有效力
** 应承认当事人在根据外国法律所得权利

=== 当代国际私法

其余部分未见于课件，不应该考，从略。

==== 美国冲突法革命

===== 柯里的政府利益分析说（governmental interests analysis）

===== 里斯的最密切联系说


== 冲突规范

概念：指明某种国际民商事法律关系应适用何国实体法来调整的法律规范。

=== 结构

* 范围（category）：冲突规范所要调整的某种涉外民事法律关系
* 系属（attribution）：调整该类民事法律关系应该适用的法律
** 联结点（point of contact）：冲突规范赖以确定涉外民事法律关系应该适用某一地域法律的一种事实因素

例如：侵权（范围）依（关联词）**侵权行为地（连接点）法（系属）**。

==== 联结点

连结点有客观连结点和主观连结点之分。

连结点根据其在特定的民商事法律关系中是否可以变化，分为静态连结点和动态连结点。

==== 系属公式

. 属人法（lex personalis）
.. 本国法（lex patriae）：常见于大陆法系国家
.. 住所地法（lex domicilii）：普通法、我国现行原则
. 物之所在地法（lex rei sitae）
. 行为地法（lex loci actus）
. 当事人合意选择的法（lex voluntatis）
. 法院地法（lex fori）
. 旗国法（law of the flag）
. 最密切联系地法（the law with which a relationship is most closely connected）

=== 类型

单边冲突规范（unilateral conflict rules）:: 其系属直接规定适用某国法律的冲突规范。

双边冲突规范（bilateral conflict rules）:: 其系属含有一个抽象的连结点，结合案情才能确定准据法的冲突规范。

重叠适用的冲突规范（cumulative conflict rules）:: 其系属中连结点有两个或两个以上，且须**同时适用**才能确定准据法的冲突规范。

选择适用的冲突规范（alternative conflict rules）:: 其系属中连结点有两个或两个以上，只需**选择其一**就能确定准据法的冲突规范。

== 准据法（applicable law, lex causae）

准据法（lex causae）:: 经冲突规范指定援用来具体确定民商事法律关系当事人权利与义务的特定的实体法。

[quote,《法律适用法》第6条]
____
涉外民事关系适用外国法律，该国不同区域实施不同法律的，适用与该涉外民事关系有最密切联系区域的法律。
____

== 适用冲突规范的制度


=== 定性（qualification）

定性（qualification）:: 又称为识别（characterization）或归类(classification），是指在适用冲突规范时，依照某一法律观念对有关事实或问题进行分析，将其归入一定的法律范畴，并对有关冲突规范的范围或对象进行解释的过程。

[quote,《法律适用法》第8条]
____
涉外民事关系的定性，适用法院地法律。
____

[quote,《法律适用法解释(一)》第11条]
____
案件涉及两个或者两个以上的涉外民事关系时，人民法院应当分别确定应当适用的法律。footnote:[这一规定实际上是明确了在我国司法实践中应适用识别分割制。]
____


=== 反致（renvoi）

广义的反致:: 法院地国在根据本国冲突规范适用外国法的过程中，接受了该外国法冲突规范的指定，适用本国实体法或第三国实体法的制度。

狭义的反致（remission）:: 直接反致。

==== 分类

转致（transmission）:: 又称“二级反致”，是指对于某一涉外民商事案件，依法院地国冲突规范应当适用某外国法，而依该外国冲突规范的规定，需适用第三国法，如果法院地国最终适用了该第三国的实体法，这种适用法律的过程就叫作转致。

[mermaid]
----
flowchart LR
A --> B --> C
----

直接反致（remission）:: 简称为“反致”“一级反致”，是指法院审理某一涉外民商事案件时按照本国的冲突规范应适用某一外国法，而该外国法中的冲突规范却指定此案件应适用法院地国的实体法，法院据此适用了本国的实体法。


[mermaid]
....
flowchart LR
A --> B --> A
....


间接反致（indirect remission）:: 又称为“大反致”,是指对于某一涉外民商事案件，依法院地国冲突规范的规定，应当适用某外国法，而依该外国法中的冲突规范的规定，应适用第三国法律；但是，依第三国冲突规范的规定，却又应当适用法院地国法律。最后，法院地国适用了其本国实体法。

[mermaid]
....
flowchart LR
A --> B --> C --> A
....

包含直接反致的转致:: 是指对某一案件，依法院地国冲突规范指定应适用某外国法，而依该外国冲突规范指定应适用第三国法律，但第三国冲突规范反向指定应适用该外国法律，最后法院地国适用该外国的实体法律处理了案件。这种情形是转致的一种特殊情形。

[mermaid]
....
flowchart LR
A --> B --> C
C --> B
....

我国《法律适用法》第9条规定：“涉外民事关系适用的外国法律，不包括该国的法律适用法。”该条规定表明，**我国**司法实践中**禁止反致与转致**。

=== 外国法的查明（ascertainment of foreign law）

. 查明主体
.. 当事人选，当事人查明
.. 否则，审案机关查明
. 无法查明
.. 后果：适用中国法律
.. 认定
... 无法查明，当事人查明的，在确定期限内无正当理由提供
... 审案机关查明的，用尽规定途径无法获得
. 查明途径：当家机协使领馆，使领馆经最高院
. 费用：从约定，无约定酌情定
. 当事人、机构或专家查明
.. 外国法的具体规定或者判例全文
.. 外国法来源和效力的说明
.. 机构和专家的资质证明和无利害关系书面声明
. 外国法的审查和认定
.. 程序
... 应在法庭上出示并听取当事人的意见
... 机构和专家可出庭或在线发表对外国法的意见
... 裁判文书应载明外国法的查明过程及内容
.. 标准
... 当事人无异议，法院可确认
... 当事人有异议并说明理由，法院可补充查明
... 法院应当确认生效裁判已认定的外国法，除非有足以推翻的相反证据

==== 查明途径（当家机协使领馆，使领馆经最高院）

对于人民法院查明外国法的途径，《法律适用法解释(一)》第15条第1款只是进行了非穷尽性的列举。但2024年1月1日生效的《法律适用法解释(二)》第2条第1款则明确规定了外国法查明的七种途径：(1)由当事人提供；(2)通过司法协助渠道由对方的中央机关或者主管机关提供；(3)通过最高人民法院请求我国驻该国使领馆或者该国驻我国使领馆提供；(4)由最高人民法院建立或者参与的法律查明合作机制参与方提供； (5)由最高人民法院国际商事专家委员会专家提供；(6)由法律查明服务机构或者中外法律专家提供；(7)其他适当途径。人民法院通过前款规定的其中一项途径无法获得外国法律或者获得的外国法律内容不明确、不充分的，应当通过该款规定的不同途径补充查明。人民法院依据本条第1款第1项的规定要求当事人协助提供外国法律的，不得仅以当事人未予协助提供为由认定外国法律不能查明。

=== 公共秩序保留

公共秩序保留:: 法院地国根据本国的冲突规范应当适用外国法时，如果外国法的适用或外国法的适用结果会违反法院地国的公共秩序时，限制或排除该外国法适用的制度。

我国《法律适用法》第5条规定：“外国法律的适用将损害中华人民共和国社会公共利益的，适用中华人民共和国法律。”

=== 法律规避（evasion of law）

法律规避（evasion of law）:: 涉外民商事法律关系当事人为了实现利己的目的，故意制造或改变构成法院地国冲突规范连结点的具体事实，以避开本应适用的对其不利的准据法而使对其有利的法律得以适用的行为。

《法律适用法解释(一)》第9条规定：“一方当事人故意制造涉外民事关系的连结点，规避中华人民共和国法律、行政法规的强制性规定的，人民法院应认定为不发生适用外国法律的效力。”

. 构成要件（我国）
.. 故意
.. 制造或变更联结点
.. 避开中国**法律或行政法规**的**强制**性规定
.. 使对自己有利的外国法得以适用（既遂）
. 后果：适用中国法

=== 直接适用的法

《法律适用法》（2011）第4条规定：“中华人民共和国法律对涉外民事关系有强制性规定的，直接适用该强制性规定。”

《法律适用法解释(一)》第8条对《法律适用法》第4条所称之“直接适用的法”的范围予以了限制。有下列情形之一，涉及中华人民共和国社会公共利益、当事人不能通过约定排除适用、无须通过冲突规范指引而直接适用于涉外民事关系的法律、行政法规的规定，人民法院应当认定为《法律适用法》第4条规定的强制性规定：(1)涉及劳动者权益保护的；(2)涉及食品或公共卫生安全的；(3)涉及环境安全的；(4)涉及外汇管制等金融安全的；(5)涉及反垄断、反倾销的；(6)应当认定为强制性规定的其他情形。

总结：**一保护两反三安全**。“一保护”是指保护劳动者权益，“两反”是指反垄断、反倾销，“三安全”是指食品或公共卫生安全、环境安全和金融安全。

== 国际民商事法律适用 


=== 原则性规定

==== 意思自治原则

《法律适用法》和《法律适用法解释(一)》对法律适用中的意思自治原则规定如下：

. 只有法律允许当事人意思自治的，当事人的法律选择才有效，且法律适用中的意思自治不受实际联系原则的限制(法律另有规定的除外)
. 当事人意思自治的最晚时间为一审法庭辩论终结前，各方当事人援引相同法律且未提出法律适用异议的，视为已经达成意思自治
. 国际条约(包括尚未对中国生效的国际条约)可以成为当事人意思自治的对象

==== 最密切联系原则

《法律适用法》第2条规定：“涉外民事关系适用的法律，依照本法确定。其他法律对涉外民事关系法律适用另有特别规定的，依照其规定。本法和其他法律对涉外民事关系法律适用没有规定的，适用与该涉外民事关系有最密切联系的法律。”

“最密切联系原则”是确定准据法的**兜底**性原则。

=== 民事主体的法律适用

[cols="1,a,a", options="header"]
|===
| 主体
| 自然人
| 法人及其分支机构

| 基本原则 
| 经常居所地法（婚姻家庭、继承关系除外）
| 登记地法

| 例外
| 
. 票据当事人的行为能力，适用其本国法律
. 自然人从事民事活动（票据活动），依照经常居所地法（本国法）为无民事行为能力，依照行为地法律为有民事行为能力的，适用行为地法律
| 主营业地与登记地不一致的，可以适用主营业地法或登记地法
|===

口诀：自然人用经居地，居无行有行为地。法人登记营业地，排除机构所在地。

=== 时效、代理和信托的法律适用

. 时效：与与基础法律关系的准据法一致
. 代理
.. 委托代理允许意思自治优先
.. 代理内部关系(被代理人与代理人的民事关系),适用代理关系发生地法
.. 代理外部关系(代理行为效力之争),适用代理行为地法
. 信托：（按顺序）意思自治→信托财产所在地法或者信托关系发生地法

口诀：时效基础法一致，委代信托可自治。代理内部关系地，代理外部行为地，信托财产或关系。

=== 物权的法律适用

. 基本原则
.. 不动产适用物之所在地法
.. 动产：（按顺序）意思自治→法律事实发生时物之所在地法
. 例外
.. 船舶
... 原则：旗国法
...  例外
.... 优先权footnote:[中国为“工人税救财”五种。优先>留置>抵押。]适用法院地法
.... 光船租赁以前或期间设立船舶抵押权的，适用原登记国法
.. 民用航空器
... 原则：登记国法
... 例外
.... 优先权适用法院地法
.... 运输中动产(按顺序)意思自治→运输目的地法
.. 有价证券：权利实现地法或者最密切联系地法
.. 权利质权：设立地法律

口诀：不动物之所在地，动产自治获得地。船旗飞登优法院，光租抵押原登记。运输自治目的地，证券实现密联地。权利质权设立地。

=== 债权的法律适用 

==== 合同债权

《法律适用法》第41条规定：“当事人可以**协议选择**合同适用的法律。当事人没有选择的，适用履行义务最能体现该合同特征的一方当事人经常居所地法律或者其他与该合同有**最密切联系**的法律。”

我国《法律适用法》第41条首先明确了应当依据**“特征性履行原则”**来确定涉外合同的最密切联系地，即根据合同的特殊性质，以及某一方当事人履行的义务最能体现合同的本质等因素，确定与合同最密切联系的国家或者地区的法律作为合同的准据法。

===== 意思自治优先原则的例外

. 在中国境内履行的**中外合资经营企业合同、中外合作经营企业合同和中外合作勘探开发自然资源合同**，适用中国法律
. *消费者合同*
.. 由消费者选择，且只能选择商品、服务提供地法
.. 消费者无选择，看经营者在消费者经常居所地有没有从事相关经营活动
... 有经营，适用消费者经常居所地法
... 无经营，适用商品、服务提供地法
. *劳动合同*
.. 劳动聘用合同
... 能确定劳动者工作地的，适用劳动者工作地法
... 不能确定劳动者工作地的，适用用人单位主营业地法
.. 劳务派遣合同
... 能确定劳动者工作地的，适用劳动者工作地法或劳务派出地法
... 不能确定劳动者工作地的，适用用人单位主营业地法或劳务派出地法

口诀（消费者合同）：限买限选提供地，不选买居看经营。买居经营买居地，买居无营提供地。

口诀（劳动合同）：劳动合同禁选法，工地确定工作地，工地不定营业地，派遣还可派出地。

==== 侵权债权

. 基本原则
.. 意思自治→共同经常居所地法→侵权行为地法
. 例外
.. 船舶碰撞
... 船旗国法：同一国籍的船舶碰撞
... 侵权行为地法：不同国籍船舶碰撞于内水或领海
... 法院地法
.... 不同国籍船舶碰撞于公海
.... 海事赔偿责任限制
.. 民用航空器侵权
... 侵权行为地法：民用航空器对地面、内水或领海水面第三人侵权
... 法院地法：民用航空器在公海上空对水面第三人侵权
.. 产品责任
... 被侵权人可选择法律，但只能选择侵权人主营业地法或损害发生地法
... 被侵权人无选择，看侵权人在被侵权人经常居所地有没有从事相关经营活动
.... 有经营，适用被侵权人经常居所地法
.... 无经营，适用侵权人主营业地法或损害发生地法
.. 侵害人格权：被侵权人经常居所地法
.. 知识产权：意思自治(只能选择法院地法)→被请求保护地法(原告诉请保护的其知识产权有效地)

====  准合同

口诀：自治共居发生地。

=== 商事关系的法律适用

==== 票据

. 票据行为
.. 原则：行为地法
.. 例外：支票出票时的记载事项，经当事人协议也可以适用付款地法
. 票据追索权行使期限：出票地法
. 持票人责任：付款地法
. 票据丧失时权利保全程序：付款地法

口诀：票据行为行为地，支票出票可协议。追索期限出票地，其他统统付款地。

==== 海事与民航

海事与民航关系法律适用中，有关物权关系、合同之债和侵权之债法律适用的内容在前面已有详述，这里只需要补充共同海损法律适用的规定。我国《海商法》第274条规定：“共同海损理算，适用理算地法律。”

=== 知识产权的法律适用

知识产权侵权的法律适用前文也已详述footnote:[知识产权转让或许可适用合同之债法律适用的一般规定。知识产权侵权， (按顺序)意思自治(只能法院地法)→被请求保护地法。]，这里需要掌握的只剩一点：知识产权的内容和归属，适用被请求保护地法。这里的“被请求保护地法”,与前文知识产权侵权处的“被请求保护地法”含义相同，也应看原告诉请保护其在“哪里”的知识产权，或者双方就“哪里”的知识产权发生讼争。

口诀：内容归属保护地，许可转让是协议，侵权法院保护地。

=== 家庭关系的法律适用 

==== 婚姻

. 结婚
.. 结婚手续：符合婚姻缔结地法、一方当事人经常居所地法或者国籍国法的，均为有效
.. 结婚条件：（按顺序适用）共同经常居所地法→共同国籍国法→婚姻缔结地法（在一方当事人经常居所地或者国籍国缔结婚姻的）
. 离婚
.. 离婚协议：（按顺序适用）意思自治（只能选择一方经常居所地法或者国籍国法）→共同经常居所地法→共同国籍国法→办理离婚手续机构所在地法
.. 诉讼离婚：法院地法
. 夫妻关系
.. 人身关系：（按顺序适用）共同经常居所地法→共同国籍国法
.. 财产关系：（按顺序适用）意思自治（只能选择一方经常居所地法、国籍国法或主要财产所在地法）→共同经常居所地法→共同国籍国法

口诀：结婚手续任你意，诉讼离婚法院地。协离财产自治地，共居共国行为地。

NOTE: 如果夫妻双方既没有共同经常居所地，也没有共同国籍，夫妻关系应根据“最密切联系原则”(兜底性原则)来确定法律适用问题。

[NOTE]
====
广义的夫妻关系(包括结婚、婚姻存续期间的夫妻关系和离婚)法律适用的共同规律：

首先，只有离婚协议和夫妻财产关系允许意思自治，但又都限制意思自治。

其次，法律适用基本上是按照共同经常居所地法→共同国籍国法→ 行为地法(夫妻关系为最密切联系地法)的顺序确定。
====

==== 父母子女、扶养和监护

父母子女：共同经常居所地法→一方经常居所地法或国籍国法中有利于保护弱者利益的法律

扶养：一方当事人经常居所地法、国籍国法或者主要财产所在地法中有利于保护被扶养人权益的法律。

监护：一方当事人经常居所地法或者国籍国法中有利于保护被监护人权益的法律。

口诀：父母监扶重弱者，父母先用共居地。

==== 收养

程序要求：

. 外国人应通过外国收养组织向中国收养组织**转交申请**，并提供家庭情况报告和证明
. 外国人应当**亲自**来华办理登记手续。夫妻共同收养的，应当共同来华办理收养手续；一方因故不能来华的，应当书面委托另一方
. 外国人来华收养子女，应当与送养人订立**书面**收养协议

法律适用：

* 条件和手续：收养人**和**被收养人经常居所地法
* 效力：收养时**收养人**经常居所地法
* 解除：收养时**被收养人**经常居所地法或者法院地法

口诀：收养程序转亲书，条件手续重叠居，收养效力收养居，解除被收法院地。

=== 继承的法律适用

. 法定继承
.. 不动产：不动产所在地法
.. 动产：被继承人死亡时经常居所地法
. 遗嘱
.. 遗嘱方式：符合立遗嘱时或者死亡时经常居所地法、国籍国法或者遗嘱行为地法均可
.. 遗嘱效力：立遗嘱时**或者**死亡时经常居所地法**或者**国籍国法
. 遗产管理：遗产所在地法
. 绝产继承：被继承人死亡时遗产所在地法

口诀：法定不动所在地，动产死亡经居地。遗嘱方式任你意，效力国籍或居地，立时亡时皆可用，管理绝产遗产地。

== 国际民商事争议的解决 

=== 国际商事仲裁 

==== 认定仲裁协议效力

===== 制度总结

. 认定机构
.. 仲裁机构和法院都有权认定
.. 一方请求仲裁机构，另一方请求法院的，由法院裁定
.. 管辖法院：仲裁机构所在地、仲裁协议签订地、申请人住所地、被申请人住所地的中级人民法院或者专门人民法院
. 申请时间：仲裁庭首次开庭前提出（中国贸仲还要求书面形式）
. 适用法律
.. 意思自治→仲裁机构所在地法或仲裁地法→中国法
.. 适用仲裁机构所在地法与适用仲裁地法将对仲裁协议的效力作出不同认定的，法院应当适用确认仲裁协议有效的法律
. 法院认定无效的内部报告制度
.. 逐级上报至最高人民法院
.. 依最高人民法院的审核意见作出裁定

===== 法律来源

《民法典》第507条规定：“合同不生效、无效、被撤销或者终止的，不影响合同中有关解决争议方法的条款的效力。”

《仲裁法》第19条第2款规定：“仲裁庭有权确认合同的效力。”

《仲裁法》第20条第1款规定：“当事人对仲裁协议的效力有异议的，可以请求仲裁委员会作出决定或者请求人民法院作出裁定。一方请求仲裁委员会作出决定，另一方请求人民法院作出裁定的，由人民法院裁定。”

根据《仲裁法》第20条第2款的规定，无论是请求仲裁机构还是法院认定仲裁协议的效力，都应当**在仲裁庭首次开庭前提出**。

《法律适用法》第18条规定：“当事人可以**协议选择**仲裁协议适用的法律。当事人没有选择的，适用**仲裁机构所在地法律或者仲裁地法律**。”

《法律适用法解释(一)》第12条进一步明确规定：“当事人没有选择涉外仲裁协议适用的法律，也没有约定仲裁机构或者仲裁地，或者约定不明的，人民法院可以适用**中华人民共和国法律**认定该仲裁协议的效力。”

根据2018年1月1日起施行的《最高人民法院关于审理仲裁司法审查案件若干问题的规定》第13条的规定：“当事人协议选择确认涉外仲裁协议效力适用的法律，应当作出明确的意思表示，仅约定合同适用的法律，不能作为确认合同中仲裁条款效力适用的法律。”

其第14条规定：“人民法院根据《中华人民共和国涉外民事关系法律适用法》第十八条的规定，确定确认涉外仲裁协议效力适用的法律时，当事人没有选择适用的法律，适用仲裁机构所在地的法律与适用仲裁地的法律将对仲裁协议的效力作出不同认定的，人民法院应当适用确认仲裁协议有效的法律。”

2022年1月1日施行的《最高人民法院关于仲裁司法审查案件报核问题的有关规定》第2条第1款规定：“各中级人民法院或者专门人民法院办理涉外涉港澳台仲裁司法审查案件，经审查拟认定仲裁协议无效，不予执行或者撤销我国内地仲裁机构的仲裁裁决，不予认可和执行香港特别行政区、澳门特别行政区、台湾地区仲裁裁决，不予承认和执行外国仲裁裁决，应当向本辖区所属高级人民法院报核；高级人民法院经审查拟同意的，应当向最高人民法院报核。待最高人民法院审核后，方可依最高人民法院的审核意见作出裁定。”

==== 涉外仲裁程序

===== 保全

[cols="1,1,1", options="header"]
|===
| 项目 
| 财产保全 
| 证据保全

| 受理法院 
| 被申请人住所地或财产所在地的中级人民**法院** 
| 证据所在地的中级人民**法院**

| 应否提供担保 
| 应当提供，否则驳回申请 
| 法院经审查认为无须提供担保的，申请人可不提供担保
|===

===== 撤销或不予执行涉外仲裁裁决

. 期间：6个月
. 受理法院
.. 撤销：仲裁机构所在地的中级人民法院
.. 执行：被申请人住所地或者财产所在地的中级人民法院
. 理由（《民诉法291条》）
.. 无仲裁协议
.. 未得到指定仲裁员或进行仲裁程序通知，或其他因不可归责于自身原因未能陈述意见
.. 程序不符合仲裁规则
.. 超过协议范围或无权仲裁
. 不予执行或撤销需要报核，程序同不承认执行外国仲裁裁决

===== 承认与执行外国仲裁裁决

. 依据： 1958年《承认及执行外国仲裁裁决公约》（《纽约公约》）
. 我国保留
.. 中国只承认在**其他缔约国领土内**作出的（契约类或非契约类）**商事**仲裁裁决（包括临时仲裁裁决）
.. 争端双方包含**国家**的仲裁裁决不能依《纽约公约》获得承认与执行
. 申请人：当事人
. 受理法院
.. 被申请人住所地或者其财产所在地中级人民法院
.. 被申请人住所地或者财产所在地均不在我国的，申请人住所地或者与裁决的
.. 纠纷有适当联系的地点的中级人民法院
. 期间：**2年**
.. 承认和执行的申请可以同时提出，也可以分开提出
.. 只申请承认的，法院仅审查并裁定应否承认
.. 只申请承认的，申请执行的2年期间自法院承认裁定生效之日起重新计算
. 不承认的内部报核程序
.. 当事人申请
.. 裁定不承认的，报高院审查
.. 高院仍然裁定不承认的，报最高法审查

[NOTE]
====
. 对外国仲裁裁决无权撤销
. 原则上只能在当事人提出申请并满足法定条件（**程序方面**有问题）的情况下拒绝承认和执行
. 只有仲裁裁决的内容违反我国社会公共利益或者所争议事项不具有可仲裁性，法院才有权主动审查并裁定不予承认
====

=== 国际民事诉讼

==== 外国人的诉讼地位

===== 以对等为条件的国民待遇原则

===== 豁免

参阅：《最高人民法院关于人民法院受理涉及特权与豁免的民事案件有关问题的通知》。

[NOTE]
====
若民事案件涉及享有特权与豁免的主体，同时满足下列两个条件，应适用法院内部报告制度：

. 享有特权与豁免的主体是案件中的被告或第三人
. 法院经审查认为自己有管辖权
====

===== 外国当事人的身份证明
. 自然人：护照等身份证件
. 企业或其他组织
.. 两份证明
... 企业或组织的身份证明
... 代表参与诉讼的人的身份证明
.. 证明手续
... （所在国与中国有外交关系）所在国公证机构公证——中国驻该国使领馆认证
... （所在国与中国没有外交关系）所在国公证机构公证——与中国有外交关系的第三国驻该国使领馆认证——中国驻该第三国使领馆认证
... 条约约定的其他证明方式

===== 对外国当事人委托诉讼代理人的限制

//根据我国《民事诉讼法》第274条和《民诉法解释》第526条和527条的规定。（2025-06-06）
. 委托律师
.. 只能委托我国律师以律师身份参与诉讼
.. 可以委托本国律师以非律师身份担任诉讼代理人（须符合《民事诉讼法》相关规定）
. 使领馆官员
.. 受托为诉讼代理人，以个人名义，不享有特权与豁免
.. 为其本国国民在中国聘请律师或诉讼代理人，以外交代表身份，享有特权与豁免

===== 对外国人出具的授权委托书的手续要求

. 法院法官的见证下：无须履行其他手续
. 中国境内：经中国公证机构公证
. 中国境外
.. （所在国与中国有外交关系）所在国公证机构公证一中国驻该国使领馆认证
.. （所在国与中国没有外交关系）所在国公证机构公证一与中国有外交关系的第三国驻该国使领馆认证一中国驻该第三国使领馆认证
.. 条约约定的其他证明方式

===== 对诉讼语言文字的限制

[quote,《民事诉讼法》第273条]
____
人民法院审理涉外民事案件，应当使用中华人民共和国通用的语言、文字。当事人要求提供翻译的，可以提供，费用由当事人承担。
____

[quote, 《民诉法解释》第525条]
____
当事人向人民法院提交的书面材料是外文的，应当同时向人民法院提交中文翻译件。当事人对中文翻译件有异议的，应当共同委托翻译机构提供翻译文本；当事人对翻译机构的选择不能达成一致的，由人民法院确定。
____

==== 涉外民商事案件的管辖权

===== 级别管辖

. 基本原则：下沉管辖权为原则，集中管辖为例外
. 标的额管辖标准
.. 高院：50亿元以上
.. 中院
... 四大直辖市+东部沿海五省中院：4000万元以上
... 其他中院：2000万元以上
. 除外规定
.. 海事海商、知识产权、生态环境损害赔偿、环境民事公益诉讼

== 区级司法协助


=== 委托送达文书


=== 委托调取证据


=== 判决承认和执行



